
eureka:
  instance:
    hostname: bigdataserver
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://aa:abcd@localhost:8761/eureka/
#spring:
#  thymeleaf:
#    cache: false
#    mode: LEGACYHTML5
#    prefix: classpath:/web/
#    suffix: .html
#    content-type: text/html
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: password
#    timeout: 5000
#    pool:
#      max-idle: 8
#      min-idle: 0
#      max-active: 8
#      max-wait: -1
#